### PR TITLE
NOTICK DP2 merge

### PR DESCRIPTION
**Pull request by owenstanford**
NOTICK-Merge changes from DP2

### CODE REVIEW

**Comment by lankydan** [comment]
Does this need a new API version? Seems like its mainly docs so maybe its fine?

**Review by lankydan — APPROVED** [review]

**Review by josephzunigadaly — APPROVED** [review]
My change looks ok.

**Review by ronanbrowne — APPROVED** [review]
LGTM my changes

**Review by vlajos — APPROVED** [review]
My commits are OK.

**Pull request merged**
