### PR TITLE
DOC-4816: application API docs review

### PR DESCRIPTION
**Pull request by AnnaK-R3**
Please review and implement the application JavaDocs updates.

Also, the following files need descriptions to be added. Add them to this PR and contact @AnnaK-R3 for non-technical review before merging the PR to main.

- DigitalSignatureAndMetadata.java: Add descriptions to each element that appears under tabs: Constructors, Functions, and Properties in the docs aoutput.
- DigitalSignatureMetadata.java: Add descriptions to each element that appears under tabs: Constructors, Functions, and Properties  in the docs aoutput.
- SignatureSpecService.java: Add a top-level desc of what SignatureSpecService is.

### CODE REVIEW

**Comment by yarivus** [comment]
> PR title failed to match regex -> `^((CORDA|EG|ENT|INFRA|CORE)-\d+)(.*)`

@ronanbrowne - we may need to add DOC too

**Review by yarivus — DISMISSED** [review]
LGTM - we need still to adapt the github action to include DOC-xxx tickets.

**Comment by driessamyn** [comment]
@dickon , can you please approve these Crypto API doc changes?

**Comment by ronanbrowne** [comment]
@yarivus https://github.com/corda/corda-api/pull/900 to address doc ticket type addition

**Comment by ronanbrowne** [comment]
@AnnaK-R3 if you rebase with the release branch the GH action regarding the title will then pass since https://github.com/corda/corda-api/pull/900 was merged

**Review by yarivus — APPROVED** [review]
LGTM

**Review by dickon — APPROVED** [review]
LGTM, Thanks Anna, that's useful clarification on a couple of style points.

**Pull request merged**
