### PR TITLE
CORE-6471: Relocate DurableCursor & Co. from `corda-api`

### PR DESCRIPTION
**Pull request by vkolomeyko**
Package move: `net.corda.v5.base.stream` -> `net.corda.httprpc.durablestream.api`

New module: `:libs:http-rpc:http-rpc-common`.

`corda-runtime-os` PR: corda/corda-runtime-os#1980

### CODE REVIEW

**Review by conal-smith — APPROVED** [review]
lgtm

**Comment by mnesbit** [comment]
Definitely agree with moving this stuff which is a historic artifact of the way C4 worked

**Comment by vkolomeyko** [comment]
> Definitely agree with moving this stuff which is a historic artifact of the way C4 worked

Thank you @mnesbit - could we affirm this agreement with approval of the PR, such that I could merge it and release `corda-api` lock, please?

**Review by driessamyn — APPROVED** [review]
LGTM

Will leave merge to you so you can coordinate with the version lock.

**Pull request merged**
