### PR TITLE
CORE-13495, CORE-11273, CORE-11274: Merge from 5.0 up to 6da8d0e

### PR DESCRIPTION
**Pull request by kyriathar**
- merges from release/os/5.0 up to https://github.com/corda/corda-api/commit/6da8d0ef806d6193790ac127163109dce223f4ae
 - leaves out CODEOWNERS release/os/5.0  freeze change ([bfb7848](https://github.com/corda/corda-api/pull/1129/commits/bfb7848ce983042bc173d03693748c776e859429))

### CODE REVIEW

**Review by ronanbrowne — COMMENTED** [review]
codeowners file is 5.0 only, so when resolving conflict, don't accept the incoming version here
 other changes i made are fine though

**Comment by kyriathar** [comment]
Changed to leave out CODEOWNERS 5.0 freeze changes

**Review by lankydan — APPROVED** [review]

**Review by lankydan — APPROVED** [review]

**Review by mag1c-48 — APPROVED** [review]
LGTM - build only

**Review by ronanbrowne — APPROVED** [review]
lgtm (my changes brought forward )

**Pull request merged**
