### PR TITLE
CORE-7976 Move cipher-suite module from corda-api to corda-runtime-os

### PR DESCRIPTION
**Pull request by kyriathar**
runtime-os PR: [#2527](https://github.com/corda/corda-runtime-os/pull/2527)

### CODE REVIEW

**Review by chrisr3 — COMMENTED** [review]
LGTM (apart from the conflict... :wink:)

**Review by ronanbrowne — DISMISSED** [review]
LGTM (build)

**Review by mnesbit — DISMISSED** [review]
OK

**Review by mnesbit — APPROVED** [review]
OK

**Review by mcgovc — APPROVED** [review]
LGTM (build)

**Pull request merged**
