### PR TITLE
CORE-13161 Fix missing suspendable, prerequsite for demo Flows with Facades Facades

### PR DESCRIPTION
**Pull request by szymonsztuka**
Temporarily it also contains commits from runtime/os/5.1 branch.

### CODE REVIEW

**Review by yarivus — APPROVED** [review]
LGTM

**Review by yarivus — APPROVED** [review]
LGTM

**Review by yarivus — APPROVED** [review]
LGTM

**Comment by szymonsztuka** [comment]
Th PR is no longer needed after merging https://github.com/corda/corda-api/pull/1123 and https://github.com/corda/corda-api/pull/1133

**Pull request closed without merging**
