### PR TITLE
CORE-4958 Uniqueness checker backing store data type refinement

### PR DESCRIPTION
**Pull request by ifrankrui**
Uniqueness checker backing store data type change and refinement. See https://github.com/corda/corda-runtime-os/pull/2285 for more details.

### CODE REVIEW

**Review by relyafi — DISMISSED** [review]
LGTM

**Review by nkovacsx — DISMISSED** [review]
I'm happy

**Comment by relyafi** [comment]
@mnesbit please could you review on behalf of team leads (Christian is off today). This contains an API change so will need to go through the 2 phase review (approve changes then approve API bump for merge) again.

**Comment by relyafi** [comment]
@mnesbit please could you review on behalf of team leads due to the API change., Will need to go through the 2 phase review (approve changes then approve API bump for merge) again.

**Review by mnesbit — DISMISSED** [review]
OK

**Comment by ifrankrui** [comment]
Hi @relyafi, @mnesbit, I have taken a lock in `#corda-platform-api-version-lock` channel. Could you please review and approve this PR again?

**Review by relyafi — APPROVED** [review]
LGTM, needs team leads approval (@mnesbit) to be able to merge though

**Review by mnesbit — APPROVED** [review]
OK

**Review by nkovacsx — APPROVED** [review]

**Pull request merged**
