### PR TITLE
ES-91: Upgrade Gradle Version

### PR DESCRIPTION
**Pull request by knguyen-r3**
* Upgrade gradle version to 8.1 and create new gradle wrapper as part of C5 update.
* Added new files that were modified when running gradle with new version
* Update check-pr-title.yml workflow to be able to accept ES PR
* Added new dependency ordering for kotlinSourcesJar and dokkaHtmlPartial

### CODE REVIEW

**Comment by ronanbrowne** [comment]
@knguyen-r3 FYI this PR gate is failing. Something is likely different in the API for 8.1 for the task which it is failing on this will need to be investigated, see logs for exact task where issues is, regarding `./gradlew generateMultiModuleDocs ` see zip task specification https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Zip.html 
`

**Review by mcgovc — APPROVED** [review]
LGTM

**Comment by mcgovc** [comment]
Confirmed Gradle version bump on [Gradle build scan](https://gradle.dev.r3.com/s/osfl4xjghqpeo )

**Review by yarivus — COMMENTED** [review]
thx @knguyen-r3

**Pull request merged**
