### PR TITLE
CORE-18640 Remove unused crypto topics

### PR DESCRIPTION
**Pull request by bpaunescu**

### CODE REVIEW

**Review by anien — APPROVED** [review]
LGTM. If you can please ensure runtime-os runs fine with these changes, that would be great.

**Comment by bpaunescu** [comment]
@anien @Sakpal I've run the e2e tests with this change. See https://ci02.dev.r3.com/job/Corda5/job/corda5-e2e-tests/job/release%2F5.2/720/parameters/ for API Version set to what this PR has published.

**Review by anien — APPROVED** [review]
I have also run runtime-os with these api changes: https://github.com/corda/corda-runtime-os/pull/5726. 
LGTM.

**Comment by bpaunescu** [comment]
Closing and raising against 5.3

**Pull request closed without merging**
