### PR TITLE
CORE-10424 : Config changes to fix the interop processor

### PR DESCRIPTION
**Pull request by SaurabhR3**
Added required config for state and event topic

### CODE REVIEW

**Review by jmacmahonr3 — APPROVED** [review]
Looks fine to me

**Comment by szymonsztuka** [comment]
need to bump up API version

**Comment by SaurabhR3** [comment]
> need to bump up API version

Why do  we need to bump the version for this? I believe it should generate the 2.beta again once merged ?

**Review by yarivus — APPROVED** [review]
LGTM

**Comment by szymonsztuka** [comment]
> > need to bump up API version
> 
> Why do we need to bump the version for this? I believe it should generate the 2.beta again once merged ?

We exactly don't want to rebuild artifact under the same version, what if Hiberate would republish hiberante-core.5.2.2.jar twice?

**Review by szymonsztuka — APPROVED** [review]

**Comment by SaurabhR3** [comment]
> > > need to bump up API version
> > 
> > 
> > Why do we need to bump the version for this? I believe it should generate the 2.beta again once merged ?
> 
> We exactly don't want to rebuild artifact under the same version, what if Hiberate would republish hiberante-core.5.2.2.jar twice?

I believe it adds up the random_number based on some logic, and we are you using beta+ in corda-runtime-os, so it will pick the latest as there is no breaking changes. In this case it's better to avoid the version increment. I have increased it now, but this is what my opinion.

**Comment by szymonsztuka** [comment]
> > > > need to bump up API version
> > > 
> > > 
> > > Why do we need to bump the version for this? I believe it should generate the 2.beta again once merged ?
> > 
> > 
> > We exactly don't want to rebuild artifact under the same version, what if Hiberate would republish hiberante-core.5.2.2.jar twice?
> 
> I believe it adds up the random_number based on some logic, and we are you using beta+ in corda-runtime-os, so it will pick the latest as there is no breaking changes. In this case it's better to avoid the version increment. I have increased it now, but this is what my opinion.

There's no random number for client project using this dependency, this broken JAR already polluted local caches of anyone using it. Hence you need to inform anyone that there is new remote version of the artifact by bumping up this number.

**Pull request merged**
