### PR TITLE
CORE-11274 Add Java version for code examples in crypto API Javadocs

### PR DESCRIPTION
**Pull request by kyriathar**

### CODE REVIEW

**Review by dickon — CHANGES_REQUESTED** [review]
@driessamyn  pointed out in other places we have both Java and Kotlin versions, so we should probably follow that pattern for consistency.

**Comment by kyriathar** [comment]
>@driessamyn pointed out in other places we have both Java and Kotlin versions, so we should probably follow that pattern for consistency.

Example added in Kotlin too, alongside Java. Both Java and Kotlin version tested they compile and `digest` methods tested too.

**Review by dickon — APPROVED** [review]
LGTM

**Review by driessamyn — APPROVED** [review]
Approved (doc changes only, not code changes)

**Pull request merged**
